### ISSUE TITLE
Python 3 Compatibility

### ISSUE THREAD

**Issue by sparthir** [jamesbowman/raytrace#5]
I ran into some issues running this but then I realized it's because I was running Python 3.8.  As 2.x becomes more and more deprecated and less supported may I suggest we upgrade it to Python 3.x?

I have made the changes that got it working under Python 3.x and wonder if you want me to put in a pull request for you?

My version also has an updated ReadMe.md file with instructions for the packages needed.

**Comment by sparthir** [comment]
I should mention I updated this because I was using it to teach someone about coding and raytracing.  It was an awesome and not too overwhelming example.  :)

**Comment by jamesbowman** [comment]
Oh - I thought I'd switched this to 3.x - but you're right, it's 2.x.

Yes a pull request would be much appreciated, thanks a lot.

**Comment by sparthir** [comment]
Will do shortly.  Trying to debug a git issue. :)

**Comment by sparthir** [comment]
Sorry, I just realized I did one giant commit and pull request.  I can split it up if you like.  It's not too much trouble.

I didn't think that I'd be committing back when I was originally doing the changes.  I was just playing around with it for my own enjoyment at the time. :)

**Comment by sparthir** [comment]
If you want changes let me know. :)

**Comment by mahiuchun** [comment]
fwiw, `2to3` and `s/import Image/from PIL import Image/g` is enough to make it work under Python 3.

**Comment by sparthir** [comment]
> fwiw, `2to3` and `s/import Image/from PIL import Image/g` is enough to make it work under Python 3.

Yes but that's more of a shortcut to get it working.  If you want to extend the code in the future it's best to start from a better place imho. :)
